services:
    app:
      image: wordpress
      ports:
        - "80:80"
      environment:
        WORDPRESS_DB_HOST: db
        WORDPRESS_DB_USER: root
        WORDPRESS_DB_PASSWORD: root
        WORDPRESS_DB_NAME: wordpressdb
      depends_on:
        - db
    db:
      image: mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: wordpressdb
      volumes:
        - vol1:/var/lib/mysql
volumes:
  vol1:
